# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20170612_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='job_type',
            field=models.CharField(default='embosser', max_length=100, verbose_name='job type'),
        ),
    ]
