# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='can_be_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
