# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_text', models.CharField(blank=True, max_length=200)),
                ('field_has_been_set', models.BooleanField(default=False)),
                ('editing_mode', models.BooleanField(default=False)),
                ('name_is_operator_editable', models.BooleanField(default=True)),
                ('text_is_operator_editable', models.BooleanField(default=True)),
                ('required_for_full_submission', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=100)),
                ('assembly_number', models.CharField(blank=True, max_length=100)),
                ('operation_number', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(default='embosser', max_length=100, verbose_name='job type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('process_outline', models.CharField(default='None', max_length=100, verbose_name='Process Template')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grinder_manager.Job'),
        ),
    ]
