# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grinder_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assembly_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='operation_number',
            field=models.CharField(max_length=100),
        ),
    ]
