# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grinder_manager', '0002_auto_20170614_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='date_due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 14, 15, 26, 32, 24583, tzinfo=utc), verbose_name='date due'),
            preserve_default=False,
        ),
    ]
