# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grinder_manager', '0003_auto_20170614_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='editing_mode',
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_has_been_set',
        ),
        migrations.AddField(
            model_name='field',
            name='is_associated_with_a_template',
            field=models.BooleanField(default=False),
        ),
    ]
