# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grinder_manager', '0004_auto_20170614_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date due'),
        ),
    ]
