# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=3)),
                ('field_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_due', models.DateTimeField(verbose_name='date due')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embossers.Job'),
        ),
    ]
