# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 17, 59, 18, 154319, tzinfo=utc), verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(editable=False, verbose_name='date created'),
        ),
    ]
