# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='New Job', max_length=100),
        ),
    ]
