# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0003_auto_20170607_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 18, 2, 4, 582975, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
