# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0004_auto_20170607_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 1, 4, 47, 773804, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
