# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0005_auto_20170608_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 13, 57, 42, 667780, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
