# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0006_auto_20170608_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_id',
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 14, 30, 47, 356257, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
