# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0008_auto_20170608_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='editing_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='field_has_been_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 17, 25, 29, 681339, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
