# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0009_auto_20170608_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_due',
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 19, 28, 4, 864540, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
