# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0011_auto_20170608_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='full_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='only_value_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 20, 8, 3, 814235, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
