# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0015_auto_20170608_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
    ]
