# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0017_auto_20170608_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='process_outline',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
