# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0018_job_process_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name_is_operator_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='text_is_operator_editable',
            field=models.BooleanField(default=True),
        ),
    ]
