# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0019_auto_20170609_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='required_for_full_submission',
            field=models.BooleanField(default=True),
        ),
    ]
