# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0020_field_required_for_full_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='New Job', max_length=20),
        ),
    ]
