# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0021_auto_20170609_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_process_outline_been_modified',
            field=models.BooleanField(default=False),
        ),
    ]
