# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0023_auto_20170609_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='process date created'),
            preserve_default=False,
        ),
    ]
