# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0024_process_process_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='New Job', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='outlinefield',
            name='OUTLINE_field_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(default='New Process Template', max_length=100, unique=True),
        ),
    ]
