# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0025_auto_20170609_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='has_process_outline_been_modified',
            new_name='has_process_outline_been_modified_for_this_operation',
        ),
    ]
