# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0026_auto_20170609_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinefield',
            name='process',
        ),
        migrations.DeleteModel(
            name='OutlineField',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
