# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0029_auto_20170609_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process_outline',
            field=models.IntegerField(choices=[(0, 'human name'), (1, 'human name'), (2, 'human name')], default=0),
        ),
    ]
