# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0030_auto_20170609_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process_outline',
            field=models.IntegerField(choices=[(0, 'Some Name'), (1, 'Some Name'), (2, 'Some Name')], default=0),
        ),
    ]
