# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0031_auto_20170609_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process_outline',
            field=models.IntegerField(choices=[(0, 's Template'), (1, 'ss'), (2, ''), (3, 'ocess')], default=0),
        ),
    ]
