# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0033_auto_20170609_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process_outline',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
