# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0034_auto_20170609_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
    ]
