# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0035_auto_20170612_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hase_job_name_been_set',
            field=models.BooleanField(default=False),
        ),
    ]
