# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0036_job_hase_job_name_been_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='New Job', max_length=100, unique=True),
        ),
    ]
