# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0037_auto_20170612_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
