# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0038_job_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='hase_job_name_been_set',
            new_name='has_job_name_been_set',
        ),
    ]
