# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0039_auto_20170612_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
