# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0040_job_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submit_button_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
