# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0041_job_submit_button_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submit_button_disabled',
        ),
    ]
