# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0043_job_disable_submit_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='disable_submit_button',
            field=models.BooleanField(default=True),
        ),
    ]
