# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0044_auto_20170612_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='disable_submit_button',
            field=models.BooleanField(),
        ),
    ]
