# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0047_auto_20170612_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assembly_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='disable_submit_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='operation_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
