# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embossers', '0048_auto_20170612_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='has_process_outline_been_modified_for_this_operation',
            field=models.BooleanField(default=False, verbose_name='Edited Template'),
        ),
        migrations.AlterField(
            model_name='job',
            name='process_outline',
            field=models.CharField(default='None', max_length=100, verbose_name='Process Template'),
        ),
    ]
